### ISSUE TITLE
r2dbc-pool not available to be selected at project creation, but wanted by micrometer

### ISSUE THREAD

**Issue by pid42** [micronaut-projects/micronaut-starter#1535]
### Description

Launch does not provide an option to select R2DBC-Pool to be included in a project. 

Also, if the users selects r2dbc and also metrics, the generated application does not run, as `micronaut-micrometer-core`
expects `io.r2dbc.pool.ConnectionPool` to be available in runtime . 

### Task List

- [X] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [X ] Full description of the issue provided (see below)

### Steps to Reproduce

1. On launch, select `data-r2dbc`, `postgres` and `micrometer-prometheus`
2. try to run the generated application

### Expected Behaviour

Application should start without errors

### Actual Behaviour

Application crashes with runtime error

### Environment Information

- **Operating System**: MacOS
- **Micronaut Version:** 3.7.3
- **JDK Version:** coreto-11
