### ISSUE TITLE
Task 'buildNativeLambda' not found in root project

### ISSUE THREAD

**Issue by charlee-dev** [micronaut-projects/micronaut-starter#2393]
### Description

I was following the [AWS Lambda guide](https://guides.micronaut.io/latest/mn-application-aws-lambda-graalvm-gradle-kotlin.html) as Micronaut seemed a perfect fit for my use case, but when I got the the step asking me to run gradle command, the command was not present in the project.

### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem can be generated using the Wizard
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Follow the [AWS Lambda guide](https://guides.micronaut.io/latest/mn-application-aws-lambda-graalvm-gradle-kotlin.html)
2. create a project using [Micronaut Launch](https://launch.micronaut.io/) choosing bellow options:
![CleanShot 2024-03-08 at 12 44 43](https://github.com/micronaut-projects/micronaut-starter/assets/20965327/800587af-c653-4979-a7ba-b8c593ab7aa6)
3. Open project
4. Sync gradle
5. Run `./gradlew buildNativeLambda` like in the guide

### Expected Behaviour

Micronaut to start building native image

### Actual Behaviour

Error:
```kotlin
./gradlew buildNativeLambda

FAILURE: Build failed with an exception.

* What went wrong:
Task 'buildNativeLambda' not found in root project 'demo'.

* Try:
> Run gradlew tasks to get a list of available tasks.
> For more on name expansion, please refer to https://docs.gradle.org/8.5/userguide/command_line_interface.html#sec:name_abbreviation in the Gradle documentation.
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 626ms
```

### Environment Information

- **Operating System**: Mac
- **Micronaut Version:** "4.3.3"
- **JDK Version:** 21

### Example Application

- N/A just follow the guide

**Comment by sdelamo** [comment]
You may have missed that the guide tells you to select both: `aws-lambda` and `graalvm` features. 

https://micronaut.io/launch?type=DEFAULT&features=graalvm&features=aws-lambda
