### ISSUE TITLE
Server error from Launch when selecting KoTest

### ISSUE THREAD

**Issue by mfickett** [micronaut-projects/micronaut-starter#521]
### Description

When creating an app via https://micronaut.io/launch/ I get an error if I select KoTest. It says "Internal Server Error: Resource not found for path: src/test/kotlin/io/kotest/provided/ProjectConfig.kt".

### Task List

- [x] Steps to reproduce provided
- [x] Full description of the issue provided (see below)
N/A
- [ ] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github

### Steps to Reproduce

1. go to https://micronaut.io/launch/
2. Select KoTest under Test Framework
3. Click "Preview" or "Generate"

### Expected Behaviour

Launch generates a new project

### Actual Behaviour

Launch displays a red error notification that reads:

"Internal Server Error: Resource not found for path: src/test/kotlin/io/kotest/provided/ProjectConfig.kt"

### Environment Information

N/A, web site issue

### Example Application

N/A, web site issue

**Comment by jameskleeh** [comment]
Duplicates https://github.com/micronaut-projects/micronaut-starter/issues/518
